image: inetsix/runner-python:3

# variables:
#   GET_BATFISH_SERVER: docker inspect $(docker ps | grep batfish | awk '/ / { print $1 }') -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}'
#   BATFISH_SERVER: 'eval $GET_BATFISH_SERVER'
#   DOCKER_HOST: tcp://docker:2375/
#   DOCKER_DRIVER: overlay2

stages:
  - checks
  - build
  - staging
  - deploy
  - post_deployment

.ansible_bootstrap: &ansible_bootstrap
  before_script:
    - pip install -r requirements.txt
    - chmod -R 700 .

.batfish_bootstrap: &bastfish_bootstrap
  before_script:
    - python -m pip install --upgrade git+https://github.com/batfish/pybatfish.git
    - mkdir -p candidate/configs
    - cp configs/*.conf candidate/configs/

ansible:code_sanity:
  <<: *ansible_bootstrap
  stage: checks
  script:
    - ansible-playbook pb.configure.init.yml -i inventory.ini --syntax-check
    - ansible-playbook pb.configure.fabric.yml -i inventory.ini --syntax-check
    - ansible-playbook pb.configure.deploy.yml -i inventory.ini --syntax-check
    - ansible-playbook pb.configure.deploy.intended.yml -i inventory.ini --syntax-check
    - ansible-playbook pb.status.bgp.yml -i inventory.ini --syntax-check
    - ansible-playbook pb.status.lldp.yml -i inventory.ini --syntax-check

ansible:build_config:
  <<: *ansible_bootstrap
  stage: build
  script:
    - ansible-playbook pb.configure.fabric.yml -i inventory.ini 
  only:
    refs:
      - /^issue-[0-9]+.*$/
      - master
      - merge_requests
      - web
  artifacts:
    untracked: true
    paths:
      - configs/

batfish:config_analysis:
  <<: *bastfish_bootstrap
  stage: staging
  script:
    - python .ci/batfish-validation.py --batfish_server 172.17.0.3
    - echo "Status code is" $?
  only:
    refs:
      - /^issue-[0-9]+.*$/
      - master
      - merge_requests
      - web
    changes:
      - roles/*
      - host_vars/*
      - group_vars/*
  artifacts:
    untracked: true
    paths:
      - configs/

ansible:config_diff:
  <<: *ansible_bootstrap
  stage: staging
  script:
    - ansible-playbook pb.configure.deploy.intended.yml -i inventory.ini --check --diff
  only:
    refs:
      - /^issue-[0-9]+.*$/
      - master
      - merge_requests
      - web
    changes:
      - roles/*
      - host_vars/*
      - group_vars/*
  artifacts:
    untracked: true
    paths:
      - configs/

ansible:deploy_fabric:
  <<: *ansible_bootstrap
  stage: deploy
  script:
    - ansible-playbook pb.configure.deploy.intended.yml -i inventory.ini 
  only:
    refs:
      - master
      - web
    variables:
      - $ROLLBACK == "no"
  artifacts:
    untracked: true
    paths:
      - configs/

ansible:rollback:
  <<: *ansible_bootstrap
  stage: deploy
  script:
    - ansible-playbook pb.configure.init.yml -i inventory.ini
    - ansible-playbook pb.configure.deploy.intended.yml -i inventory.ini
  only:
    refs:
      - web
    variables:
      - $ROLLBACK == "yes"

ansible:check_bgp:
  <<: *ansible_bootstrap
  stage: post_deployment
  script:
    - ansible-playbook pb.status.bgp.yml -i inventory.ini 
  only:
    refs:
      - master
      - web

ansible:check_lldp:
  <<: *ansible_bootstrap
  stage: post_deployment
  script:
    - ansible-playbook pb.status.lldp.yml -i inventory.ini 
  only:
    refs:
      - master
      - web
