---
# tasks file for base-config
- name: Generate baseline configuration from template
  template:
    src: baseline.j2
    dest: "{{ buildpath }}/baseline.conf"

- name: Assembling configurations and copying to conf/
  assemble: 
    src: "{{ buildpath }}" 
    dest: "{{ buildconfig }}"

- name: Push Baseline config
  eos_config:
    provider: "{{arista_credentials}}"
    src: "{{buildconfig}}"
    replace: "config"
